server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

security:
  oauth2:
    client:
      registration:
        google:
          client-id: 500543580651-1q4081kvc0ek1rbj4a0bl0oumbra7mns.apps.googleusercontent.com
          client-secret: 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
          scope:
            - email
            - profile